name: Documentation 

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0       # fetch all history for .GitInfo and .Lastmod
#        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Dependencies
      run: |
        sudo apt-get install doxygen -y
        sudo apt-get install graphviz -y
        sudo apt-get install sphinx-doc -y
        pip3 install sphinx-rtd-theme
        pip3 install breathe
        pip3 install sphinx-sitemap

    - name: Build documentation
      working-directory: ${{ github.workspace }}
      run: |
        mkdir build && cd build
        cmake -D SLAP_BUILD_DOCS=ON ..
        cmake --build . --target doxygen

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html