name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: OS ${{ matrix.os }} - ${{ matrix.c_compiler }} - ${{ matrix.float }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        float: [float, double]
        include:
          - os: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake (Windows)
      run: |
        mkdir ${{github.workspace}}/build && cd build
        cmake -D CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -D SLAP_FLOAT=${{ matrix.float }} ..

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure .
